### ISSUE TITLE
Error: on the air video

### ISSUE THREAD

**Issue by akimkooo** [Spmart/YTAP-Bot#8]
If the video is now being demonstrated in live format (i.e. live broadcast), it does not let you download it.

If this restriction can't be bypassed, you can add a specific error text for this case: It wasn't possible to download the video because it hasn't been fully published yet, try it later.

**Comment by Spmart** [comment]
Fixed in [#6742931](https://github.com/Spmart/YTAP-Bot/commit/6742931aaba4f696f4cc043f0a564a21ff5a5375). Kinda. Already working on production.

Sometimes YouTube provide information about stream and I can detect it by zero content duration. But in other cases no information at all — like in case with 18+ videos that requires age confirmation. I handling both scenarios but I can't say with 100% probability which of the reasons didn't let me download the audio.
